version: "2"
services: 
 cassandra:
  image: cassandra:2.2.5
  ports:
    - 9042
  container_name: cassandra

 kong:
  image: kong
  restart: always
  container_name: kong
  ports:
    - 8000:8000
    - 8001:8001
  depends_on:
    - cassandra
  security_opt: ["seccomp:unconfined"]
